//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.03 at 12:26:42 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.techit.services.org/user", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.services.techit.user;
